export type WorkerEnv = {
  POIZON_GATEWAY: DurableObjectNamespace
  POIZON_APP_KEY: string
  POIZON_APP_SECRET: string
  TURNSTILE_SECRET_KEY: string
  ALLOWED_ORIGINS: string
  TURNSTILE_EXPECTED_HOSTNAME: string
  TURNSTILE_EXPECTED_ACTION: string
  POIZON_REGION: 'JP'
  POIZON_CURRENCY: 'JPY'
  POIZON_BIDDING_TYPE: '25'
  POIZON_LANGUAGE: 'ja'
  POIZON_TIME_ZONE: 'Asia/Tokyo'
}
